/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_View;

import Data.data_login;
import project_View.Fm_QuenMatKhau;
import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Hoàng Huy
 */
public class Form_Dangnhap extends javax.swing.JFrame {

    /**
     * Creates new form Form_Dangnhap
     */
    public Form_Dangnhap() {
        initComponents();
        this.setTitle("Đăng nhập");
        this.setLocationRelativeTo(null);
        ImageIcon img = new ImageIcon(new ImageIcon("C:\\Users\\huyb1\\OneDrive\\Máy tính\\JAVA\\Test_PJ_Quanlybanhang\\src\\Img\\logo_login.png").getImage().getScaledInstance(logo_dangnhap.getWidth(), logo_dangnhap.getHeight(), Image.SCALE_SMOOTH));
        logo_dangnhap.setIcon(img);
        txt_hidePassword.setVisible(false);
        txt_ShowPassword.setVisible(true);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_Taikhoan = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_Password = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        logo_dangnhap = new javax.swing.JLabel();
        txtQuenMK = new javax.swing.JLabel();
        txt_ShowPassword = new javax.swing.JLabel();
        txt_hidePassword = new javax.swing.JLabel();
        checkAD = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Đăng nhập");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setText("ĐĂNG NHẬP");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(462, 23, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Tài khoản:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 85, -1, -1));

        txt_Taikhoan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_Taikhoan.setForeground(new java.awt.Color(204, 204, 204));
        txt_Taikhoan.setText("Username");
        txt_Taikhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_TaikhoanMouseClicked(evt);
            }
        });
        getContentPane().add(txt_Taikhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 114, 350, 34));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Mật khẩu:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 155, -1, -1));

        txt_Password.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_Password.setForeground(new java.awt.Color(204, 204, 204));
        txt_Password.setText("Password");
        txt_Password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_PasswordMouseClicked(evt);
            }
        });
        getContentPane().add(txt_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 184, 350, 34));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Đăng nhập");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(494, 254, -1, 42));
        getContentPane().add(logo_dangnhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 365, 309));

        txtQuenMK.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        txtQuenMK.setForeground(new java.awt.Color(255, 0, 51));
        txtQuenMK.setText("* Quên mật khẩu");
        txtQuenMK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtQuenMKMouseClicked(evt);
            }
        });
        getContentPane().add(txtQuenMK, new org.netbeans.lib.awtextra.AbsoluteConstraints(618, 225, 123, -1));

        txt_ShowPassword.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        txt_ShowPassword.setForeground(new java.awt.Color(0, 51, 204));
        txt_ShowPassword.setText("*Hiện mật khẩu");
        txt_ShowPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_ShowPasswordMouseClicked(evt);
            }
        });
        getContentPane().add(txt_ShowPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 225, 110, -1));

        txt_hidePassword.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        txt_hidePassword.setForeground(new java.awt.Color(0, 0, 255));
        txt_hidePassword.setText("*Ẩn mật khẩu");
        txt_hidePassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_hidePasswordMouseClicked(evt);
            }
        });
        getContentPane().add(txt_hidePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, 100, -1));

        checkAD.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        checkAD.setText("Admin");
        getContentPane().add(checkAD, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtQuenMKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtQuenMKMouseClicked
       Fm_QuenMatKhau qmk = new Fm_QuenMatKhau();
       qmk.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_txtQuenMKMouseClicked

    private void txt_ShowPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_ShowPasswordMouseClicked
        txt_ShowPassword.setVisible(false);
        txt_hidePassword.setVisible(true);
        txt_Password.setEchoChar((char)0);
    }//GEN-LAST:event_txt_ShowPasswordMouseClicked

    private void txt_hidePasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_hidePasswordMouseClicked
        txt_ShowPassword.setVisible(true);
        txt_hidePassword.setVisible(false);
        txt_Password.setEchoChar('*');
    }//GEN-LAST:event_txt_hidePasswordMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        data_login d = new data_login();
        String user = txt_Taikhoan.getText().trim();
        String pass = new String(txt_Password.getPassword()).trim();
        int ad;
        if(checkAD.isSelected()) ad=1;
        else ad=0;
        if(txt_Password.getPassword().toString().equals("") || txt_Taikhoan.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Không đước bỏ trống","Cảnh Báo",JOptionPane.WARNING_MESSAGE);
            txt_Password.setBackground(Color.yellow);
            txt_Taikhoan.setBackground(Color.yellow);
            return;
        }
        try {
            if(d.kiemtra(user, pass,ad)==true){
                this.setVisible(false);
                Fm_Trangchu h = new Fm_Trangchu(user,pass,ad);
                h.setVisible(true);
                JOptionPane.showMessageDialog(this, "Đăng nhập thành công");
                return;
            }else{
                JOptionPane.showMessageDialog(this, "Sai Username hoặc Password","Lỗi",JOptionPane.ERROR_MESSAGE);
                txt_Password.setBackground(Color.yellow);
                txt_Taikhoan.setBackground(Color.yellow);
            }
        } catch (Exception e) {
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_TaikhoanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_TaikhoanMouseClicked
        txt_Taikhoan.setBackground(Color.white);
        txt_Taikhoan.setText("");
        txt_Taikhoan.setForeground(Color.black);
    }//GEN-LAST:event_txt_TaikhoanMouseClicked

    private void txt_PasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_PasswordMouseClicked
        txt_Password.setBackground(Color.white);
        txt_Password.setText("");
        txt_Password.setForeground(Color.black);
    }//GEN-LAST:event_txt_PasswordMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Dangnhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Dangnhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Dangnhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Dangnhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Dangnhap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkAD;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel logo_dangnhap;
    private javax.swing.JLabel txtQuenMK;
    private javax.swing.JPasswordField txt_Password;
    private javax.swing.JLabel txt_ShowPassword;
    private javax.swing.JTextField txt_Taikhoan;
    private javax.swing.JLabel txt_hidePassword;
    // End of variables declaration//GEN-END:variables
}
